name: update migu
on:
  push:
    branches:
      - main
  # 原始的注释保留
  schedule:
    - cron: '0 * * * *'
  #schedule:
    #- cron: 0 * * * *
  workflow_dispatch:
  repository_dispatch:
    types: [mgcron]

jobs:
  main:
    name: update migu
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup Python
      run: |
          pip install requests futures

    - name: fetch and modify with Retry
      uses: nick-fields/retry@v4
      with:
        timeout_minutes: 5
        max_attempts: 2
        retry_on: timeout
        retry_wait_seconds: 30
        command: |
          python MIGU.py
          python sort_m3u.py

    - name: CommitAndPush
      run: |
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        git config --global user.email "github@github.com"
        git config --global user.name "Github Actions"

        git clone "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        cd "$REPO_NAME" || exit 1

        [ -f "../migu.m3u" ] && mv ../migu.m3u ./migu.m3u || true
        [ -f "../cctv.migu.m3u" ] && mv ../cctv.migu.m3u ./cctv.migu.m3u || true
        [ -f ../rkt.m3u ] && mv ../rkt.m3u ./rakutentv.m3u || true
        [ -f ../plt.m3u ] && mv ../plt.m3u ./plutotv.m3u || true

        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update: $(date +'%Y-%m-%d %H:%M:%S') UTC"
          git push origin main
        fi
